### PR TITLE
V2 refactor

### PR DESCRIPTION
**Pull request by Janaka-Steph**
- Trade on v1 and v2 protos
- Replace LDK/SDK by LiquidJS
- Replace Redux by Zustand 
- Use explorer's WebSocket capability

### CODE REVIEW

**Comment by tiero** [comment]
In Settings > Explorer We don't need Electrs batch Endpoint etc.. I will only have the user to set his web socket Electrum endpoint and explorer (UI wise)

**Comment by Janaka-Steph** [comment]
> In Settings > Explorer We don't need Electrs batch Endpoint etc.. I will only have the user to set his web socket Electrum endpoint and explorer (UI wise)

I remove API endpoints also?

**Comment by tiero** [comment]
> Which basically means we have to choose/hardcode Mempool or Blockstream.

We dont use the API of Esplora anymore right? Maybe only for /asset and icons but thats is Mempool anyway

**Comment by Janaka-Steph** [comment]
> > Which basically means we have to choose/hardcode Mempool or Blockstream.
> 
> We dont use the API of Esplora anymore right? Maybe only for /asset and icons but thats is Mempool anyway

The Trade class is taking explorerLiquidAPI but doesn't seem to be used.
Pegin needs both explorerLiquidAPI and explorerBitcoinAPI. 
BitcoinService (blockHeight fecthing etc) needs explorerBitcoinAPI.
Asset data are fecthed from explorerLiquidAPI.

In my opinion it is useful to keep it.

**Pull request merged**
